### PR TITLE
Add database secret engine

### PR DESCRIPTION
**Pull request by Dudesons**
Hi @jeffwecan,

I add some code to be able to manage the database backend.
I'm beginning to see how to write integration test, but I have to start another third party service (the database).
How can I integrate it ?

### CODE REVIEW

**Comment by jeffwecan** [comment]
Howdy @Dudesons, thanks for the PR! I'm not sure what would make sense for this project in terms of a full-blown database engine integration test (e.g., any solution would need to be viable for both local developer environments _and_ the travis-ci builds run during PRs). However I'm happy to explore what avenues we might have available to handle such a thing and I'll share anything I discover here.

**Comment by Dudesons** [comment]
Hi, @jeffwecan 
I would like to know what do you want to merge this pr ?

**Comment by jeffwecan** [comment]
We can go ahead and merge things as-is. I'll see about backfilling some tests before including these changes in the next hvac release (which I'll hopefully get time to complete over the next week or so).

**Comment by doszeta** [comment]
Hello, hvac team, I am getting errors when calling generate_credentials() in hvac0.9.1.

source:            new_key_dict = orphan_hvac_client.secrets.database.generate_credentials(name=role,
                                                                                    mount_point=service_creds_path)
Exception:
  File "/usr/local/lib/python3.7/site-packages/hvac/api/vault_api_category.py", line 42, in __getattr__
    raise NotImplementedError('"%s" auth method class not currently implemented.')

Can you confirm if this is a true issue?

Can you

**Comment by drewmullen** [comment]
Hey @doszeta 

Yeah this is a known issue: https://github.com/hvac/hvac/issues/454

With a fix hopefully being released this week: https://github.com/hvac/hvac/pull/455

**Pull request merged**
