### PR TITLE
Make returned responses more consistent

### PR DESCRIPTION
**Pull request by llamasoft**
This is another big PR so apologies in advance.  This PR fixes issue #525 and arises from the discussion therein.

This PR does one thing: create a new JSONAdapter and makes it the default.  The "JSON adapter" works just like the previous "Request" adapter except the return value uses the following logic:

    if response.status_code == 200:
        try:
            return response.json()
        except ValueError:
            pass
    return response

The net result is that _all_ client functions now have consistent logic regarding what they return. 
 As a result, all instances of the following client logic have been removed:

    return response.json()

and 

    if response.status_code == 204:
        return response
    else:
        return response.json()

This _will_ likely cause some breaking changes for some users, especially with regards to the direct `client.[read,list,write,delete]` methods as they will no longer throw a ValueError from assuming the response _always_ contains a JSON body.

### CODE REVIEW

**Comment by llamasoft** [comment]
I just had the last-second realization that the `login` method on the Adapter base class doesn't make sense.  The `request` method it depends on is abstract, so we have zero guarantees about the object type it returns.  Instead, I've moved the token extraction logic to a separate abstract method, `get_login_token`.

I also forgot to mention in the original PR that I added an adapter option called `ignore_exceptions` that optionally overrides the `raise_exception` parameter passed to `request`.  This allows a way to suppress exceptions and receive a raw Response object (normally not possible because the `raise_exception` argument isn't accessible).

**Comment by llamasoft** [comment]
I just realized an additional breaking change regarding this PR: the `lookup_*` methods (e.g. `client.secrets.identity.lookup_[entity|group]`) now return a Response[204] (truthy) instead of None (falsy) if the lookup returned no results.  

Unfortunately, I can't think of a good way to resolve this issue.  The Requests Adapter is created from a user-specified class so we can't assume in advance what sort of data type it will return.  
Honestly, given that we can't guarantee return types, we probably shouldn't be interacting with response objects _at all_, including the helpers on `read_*` methods that return `response.get('data')`.

What are your thoughts on this matter?  I can revert the `lookup_*` to return None on 204 responses, but that logic may end up causing issues with custom adapters.

**Comment by llamasoft** [comment]
Any word on if `response.get('data')` should be removed as well?  It's used in a few places, but not in others.  In my personal experience, it made return values unpredictable.  For example, most `read_*` methods use it, but `lookup_*` methods don't.

Unfortunately, removing them _will_ be a breaking change for some users.

**Comment by jeffwecan** [comment]
> Any word on if response.get('data') should be removed as well? 

I suppose I feel it makes most sense to return the entire response in all cases. In general, this module is intended to be a pretty basic wrapper for Vault API (at least as far as I'm concerned).

**Comment by drewmullen** [comment]
I agree with @jeffwecan . we had explored the idea of making all returns just the `data` portion but there are some useful values provided from vault that shouldnt be stripped (see below).

https://github.com/hvac/hvac/issues/483#issuecomment-509199918

**Comment by Lucas-C** [comment]
This looks like an nice improvement !
What is the status of this PR ? :)

**Comment by jeffwecan** [comment]
@Lucas-C: I figure it is about time to get this PR put in place! :D 

Will start working on getting it trued back up with the current state of the develop branch...

**Comment by jeffwecan** [comment]
Planning on merging this in today. To close the loop on returning the entire response dicts versus only the data key: I still want to see use move to the former in all places eventually. However I'd rather tackle that in another PR / release since its most certainly a breaking change (as @llamasoft alluded to).

**Comment by trishankatdatadog** [comment]
Okay, this one was really confusing, because the [documentation](https://github.com/hvac/hvac/blob/973c37d2624ef26cdecbff7a6cf8ba62285bdb1e/docs/usage/secrets_engines/transit.rst), which really copies doctstrings from the source code, still says to expect `requests` responses instead of the JSON body for non-204 responses. Should we update the docstrings?

**Comment by jeffwecan** [comment]
I would imagine so, and sorry for the added confusion! @trishankatdatadog, I went ahead and quoted your comment into a new issue (#537) and will try to get a review of docstrings, etc. done, and any incorrect return types updated, sometime over the next week or so. (Though contributions along those lines are of course also very welcomed. ☺)

**Comment by trishankatdatadog** [comment]
> I would imagine so, and sorry for the added confusion! @trishankatdatadog, I went ahead and quoted your comment into a new issue (#537) and will try to get a review of docstrings, etc. done, and any incorrect return types updated, sometime over the next week or so. (Though contributions along those lines are of course also very welcomed. ☺)

Thanks! Also wrong [link](https://github.com/hvac/hvac/issues/604) for issue 🙂

**Pull request merged**
