### PR TITLE
:pencil: Add HTTP/2+ use case into the advanced usage section

### PR DESCRIPTION
**Pull request by Ousret**
That PR addresses a question from the community regarding the evolution of the HTTP backend. Still, It's a workaround, but it's a start. 

Niquests is a drop-in replacement for Requests that offers an escape hatch for hvac users who desire to leverage recent HTTP capabilities. The documentation now showcases two workarounds for the limitations imposed by Requests.

- Using Niquests's Session directly
- Create a hvac adapter around Niquests

Linked to https://github.com/hvac/hvac/issues/807#issuecomment-1843605848

This alternative HTTP backend brings a lot of enhancement, I am sure that we'll find some synergies.

### CODE REVIEW

**Comment by Ousret** [comment]
Hello again,

FYI you could be potentially interested in knowing that the newest release of Niquests support secure/encrypted DNS, amongst other things.
Due to the critical nature of this project in terms of security, this is worth mentioning, so I think.

```python
import niquests

s = niquests.Session(resolver="doh+google://", multiplexed=True)
...
```

**Comment by briantist** [comment]
Sure feel free to add that to this PR!
I hope to review it soon, I will probably edit it slightly to maybe add a note or change sections around so that there's a place for this kind of unofficial things, just so we can be clear that it's user-contributed and can't necessarily be supported by `hvac`'s maintainers. I'll think about how exactly to do group that.

**Comment by briantist** [comment]
Ok! So, I created a whole new top-level section for user-contributed use cases like these, and yours will be the first. I loved your doc into there.

I made some other minor changes:
- (first, updated your branch with changes from `main`)
- changed a little formatting
- added/updated some links
- updated the contributing guide to better describe how to build docs locally

If you'd like to tweak any the wording or the links, please go ahead. I chose your project's "issues" link as the "support" link but if there's a better place, please update the link.

There's only one other tweak I'd like to ask you to do, and that's change the multiplexing code sample to not have to scroll horizontally, if possible. Maybe it's only on my screen? Not sure, please take a look when you can.

You can render the documentation locally by following the instructions in the contributor guide (use some of the steps added in this PR 😅).

---

**One other request:** unless you really need or want to, please do not squash commits locally. We squash-and-merge all of our PRs so the individual commits won't matter on the merge. 

Squashing locally makes it a little harder for me to review; I'd rather be able to see the individual changes, especially as PR development goes on.

If you must squash locally, the PR will still be reviewed it just may take longer :)

**Comment by Ousret** [comment]
I am okay with your changes.
Also did what I can to reduce horizontal scrolling for smaller screen.

**Review by briantist — APPROVED** [review]
thanks so much for this contribution @Ousret !

**Pull request merged**
