### PR TITLE
Add GCP Auth Method Class

### PR DESCRIPTION
**Pull request by seanmalloy**
No unit or integration tests yet. Code
has not been tested yet.

### CODE REVIEW

**Comment by jeffwecan** [comment]
Hullo again @seanmalloy! I am happy to see some more GCP-related API routes getting coverage here.  :D

So in https://github.com/hvac/hvac/pull/242/ I'm hoping to establish a different pattern for how auth (and ultimately secret methods) are organized. Given that, and assuming the new pattern being proposed doesn't raise any general concerns on your part, I'd love to see these GCP method additions follow that same sort of pattern. I.e., instead of adding new methods to the quite large `Client` class, we could add a `hvac.api.auth.gcp.Gcp` class to hold these methods. Since this is a new development without corresponding updates to our [contributing guidelines](https://github.com/hvac/hvac/blob/master/CONTRIBUTING.md), I figure we could either:

* Evaluate this PR's changes as-is once test coverage has been included. Assuming everything checks out, we could merge the changes as they stand and I would then be happy to refactor things before the next release. Since I'm hoping to reduce the amount of code in the `Client` class, I wouldn't want to cut a release including these methods in that class. (Once folks start calling the methods in one location, its tricky to migrate them to a different source file without risking breaking external usage relying on that status quo.)
* If you're down to follow the same sort of pattern being included with https://github.com/hvac/hvac/pull/242/ and update these changes to match, I'd be happy to help provide guidance or otherwise provide any clarification should anything be unclear.

**Comment by seanmalloy** [comment]
@jeffwecan sounds good. I can change the GCP auth code to use your new pattern. I should be able to start working on this PR again later this week.

**Comment by jeffwecan** [comment]
@seanmalloy 👍. Feel free to pull in all the recent GCP additions to a new class or just the bits you're looking to add here. Either is fine by me.

For what it is worth, I've been using a small helper script to scrape Vault API docs (e.g., https://www.vaultproject.io/api/auth/gcp/index.html) and stub out classes based on that content. So if it is helpful, here is a rough pass of an autogenerated `Gcp` class: https://github.com/jeffwecan/hvac/tree/gcp_example

**Comment by seanmalloy** [comment]
Count down to ready for review ...

- [ ] configure method works
- [ ] configure tests written
- [ ] read_config method works
- [ ] read_config tests written
- [ ] delete_config method works
- [ ] delete_config tests written
- [ ] create_role method works
- [ ] create_role tests written
- [ ] edit_service_accounts_on_iam_role method works
- [ ] edit_service_accounts_on_iam_role tests written
- [ ] edit_service_accounts_on_iam_role method works
- [ ] edit_service_accounts_on_iam_role tests written
- [ ] edit_labels_on_gce_role method works
- [ ] edit_labels_on_gce_role tests written
- [ ] read_role method works
- [ ] read_role tests written
- [ ] list_roles method works
- [ ] list_roles tests written
- [ ] delete_role method works
- [ ] delete_role tests written
- [ ] login method works
- [ ] login tests written
- [ ] deprecated login method works
- [ ] deprecated login tests written

**Comment by jeffwecan** [comment]
Hey @seanmalloy, Since we're coming up on the end of the month / about when I wanted to cut the 0.6.5 hvac release, I may try to get the work you've done already over the finish line and push up some commits to your branch if you don't mind. So if I don't hear back with any objections by next Monday, I'll probably go that route 👍

**Comment by jeffwecan** [comment]
@seanmalloy: I tried to get these additions mostly filled out. Unless you see any issues with the commits I tacked on, I'll get this merged in for the next hvac release over the next day or so.

**Pull request merged**
