### PR TITLE
Remove deprecated python syntax

### PR DESCRIPTION
**Pull request by dhuckins**
this PR removes older/deprecated python syntax from the code base
specifically:
- updates metaclass https://docs.python.org/3/library/2to3.html#to3fixer-metaclass
- remove old `abc.abstractproperty` decorator https://docs.python.org/3/library/abc.html#abc.abstractproperty

### CODE REVIEW

**Comment by briantist** [comment]
There's a problem with the way we do caching of the virtual environment in our workflows. I'm going to put up a PR for that and then I'd like this to be re-based so we can run the tests again.

**Comment by briantist** [comment]
@dhuckins with #913 merged, would you mind rebasing from `develop` and pushing again?

**Comment by dhuckins** [comment]
should be all set! (not sure what's happening with codecov here... 🤷 )

**Comment by colin-pm** [comment]
Small nitpick, do you mind rebasing your two commits on top of develop? I'd like to avoid having any merge commits included in our development branch. Otherwise change lgtm, thanks for the PR!

**Comment by briantist** [comment]
> Small nitpick, do you mind rebasing your two commits on top of develop? I'd like to avoid having any merge commits included in our development branch. Otherwise change lgtm, thanks for the PR!

I've disabled the merge commit method for this repository (hope that's ok) so that the default is now "Squash and merge" which will eliminate any merge commits in `develop`.

> should be all set! (not sure what's happening with codecov here... 🤷 )

I've been trying to figure out the coverage issues too. All I can tell so far is that the inexplicable coverage drops all seem to be in files related to enterprise features. I don't see why that would be happening though since the enterprise tests were turned off a while ago so those coverage drops should already be the baseline. Maybe when we re-enable those tests this issue will go away, but I can't be sure yet.

**Review by colin-pm — APPROVED** [review]

**Pull request merged**
