### PR TITLE
[WIP] Implement Transit engine (#302)

### PR DESCRIPTION
**Pull request by alexandernst**
This is still a WIP. Implements #302

### CODE REVIEW

**Comment by alexandernst** [comment]
@jeffwecan I see that there are some `transit`-related methods in `api.v1.__init__`, at lines 2267-2699.
What are those? Should I delete them?

**Comment by alexandernst** [comment]
@jeffwecan The code per-se (no unit test atm) should be ready. Can you check it and verify if everything is ok?

**Comment by jeffwecan** [comment]
Sure, I'll scope it out as I have some more time. I'm also fine with skipping unit tests provided the integration tests cover the code reasonably enough. For the original `Client` class methods, you can mark them deprecated with a decorator like so: https://github.com/hvac/hvac/blob/master/hvac/v1/__init__.py#L2691-L2696

That way folks have a chance to update their usage before we drop those method entirely.

**Comment by alexandernst** [comment]
@jeffwecan 👍 Deprecated methods. Ping me if this PR needs more love!

**Comment by alexandernst** [comment]
Oh, I just saw the CI errors. Do you want me to remove the tests? @jeffwecan

**Comment by jeffwecan** [comment]
Sure! That makes sense to me.

**Comment by alexandernst** [comment]
@jeffwecan Everything is green now! 👍 ✅

**Comment by jeffwecan** [comment]
Thanks @alexandernst! I am about to add in some changes that refactor how auth, secrets, and system backend classes are organized. Once I get those sorted I'll look to merge this in. Should be over the next day or two.

**Comment by jeffwecan** [comment]
In the meantime, do you mind if I push some changes accommodating that refractor to your branch as needed?

**Comment by alexandernst** [comment]
@jeffwecan Sure, feel free to add whatever you need 👍 😄

**Comment by alexandernst** [comment]
\o/

**Pull request merged**
