### PR TITLE
change bin download to enterprise

### PR DESCRIPTION
**Pull request by drewmullen**
use the trial vault enterprise binary which expires after 30 minutes

### CODE REVIEW

**Comment by jeffwecan** [comment]
Per the conversation in [https://gitter.im/hvac/community](gitter.im/hvac/community), I was able to get tests passing locally on my end with some interim tweaks. Still need to work out better long-term solutions and wait to see how the Travis build of my working branch turns out:

* Branch: https://github.com/hvac/hvac/compare/develop...jeffwecan:enterprise_trial_ci?expand=1
* Travis build: https://travis-ci.org/jeffwecan/hvac/builds/546556693

**Comment by drewmullen** [comment]
looks right to me. thanks for investigating. finding that bit about `vault -version` checks would have take me a bit.

if we ever wanted to work consul back into the test framework, now that we have enterprise, we could do some interesting stuff with DR / replication.

**Comment by drewmullen** [comment]
my local tests started working after i applied the `test_gcp.py` changes you made. thanks!

**Comment by jeffwecan** [comment]
Another wrinkle: looks like Hashicorp doesn't have a 0.11.6 version of the enterprise binary published to S3:

```
$ tests/scripts/install-vault.sh ${HVAC_VAULT_VERSION}
+DEFAULT_VAULT_VERSION=0.11.4
+HVAC_VAULT_VERSION=0.11.6
++tr '[A-Z]' '[a-z]'
+[[ 0.11.6 == \h\e\a\d ]]
+install_vault_release
+mkdir -p /home/travis/bin
+cd /tmp
+curl -sOL https://s3-us-west-2.amazonaws.com/hc-enterprise-binaries/vault/ent/0.11.6/vault-enterprise_0.11.6%2Bent_linux_amd64.zip
+unzip vault-enterprise_0.11.6%2Bent_linux_amd64.zip
Archive:  vault-enterprise_0.11.6%2Bent_linux_amd64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of vault-enterprise_0.11.6%2Bent_linux_amd64.zip or
        vault-enterprise_0.11.6%2Bent_linux_amd64.zip.zip, and cannot find vault-enterprise_0.11.6%2Bent_linux_amd64.zip.ZIP, period.
The command "tests/scripts/install-vault.sh ${HVAC_VAULT_VERSION}" failed and exited with 9 during .
```
(via: https://travis-ci.org/jeffwecan/hvac/jobs/546556696)

If it came down to it, I wouldn't be opposed to drop that version from the Travis test matrix. It is in need of some tidying up in any case to get the latest Vault versions covered...

**Comment by jeffwecan** [comment]
To be clear, re: Consul and the Vault HA integration test cases, it would be nice to keep them; I just didn't have enough time to determine exactly what about that set up wasn't playing nicely with the enterprise trial Vault set up. So if we toggle them off to unblock other additions for now, I'll at least file an issue as reminder to me to get them sorted out down the line.

For context, they were added in the first place to help prevent regressions like this one: https://github.com/hvac/hvac/issues/339 -> https://github.com/hvac/hvac/pull/347

**Comment by drewmullen** [comment]
yeah i wanted to ask you about how you determine which versions to keep testing. one way to think about it could be to establish a date, say 6 months, and we continue testing against previous versions but once theyre past the 6 month mark, if they fail, we remove them from testing and update our "supported versions" matrix

**Comment by drewmullen** [comment]
closing due to @jeffwecan [stealing my PR idea](https://github.com/hvac/hvac/compare/develop...jeffwecan:enterprise_trial_ci?expand=1) and taking all my fake internet points ;) jk

thanks for solving this problem, jeff! looking forward to expanding hvac functionality to include more enterprise features!

**Pull request closed without merging**
