### PR TITLE
Fix v2 list_secrets method

### PR DESCRIPTION
**Pull request by mikehmbn**

### CODE REVIEW

**Review by jeffwecan — COMMENTED** [review]
This change looks good but could you please leave out the version and changelog updating commits? We're still doing a [mix of manual steps w/ some automation](https://github.com/hvac/hvac/blob/develop/CONTRIBUTING.md#creating--publishing-releases) to handle those type of updates outside of PRs at the moment.

**Comment by mikehmbn** [comment]
@jeffwecan I removed all of the version/changelog updates. Thanks!

**Comment by jeffwecan** [comment]
My apologies, I must have read this PR incorrectly initially. Given what the [Vault API documentation states](https://www.vaultproject.io/api-docs/index#api-operations):

> You can list secrets as well. To do this, either issue a GET with the query parameter list=true, or you can use the LIST HTTP verb. 

I'm unclear how changing the request verb, especially without also including a `list=true` request param, would correctly solve the issue. Python requests can handle custom verbs just fine to my understanding: https://requests.readthedocs.io/en/master/user/advanced/#custom-verbs

**Comment by sshishov** [comment]
The proper fix for the issue is: #689

**Comment by jeffwecan** [comment]
Word, thanks @sshishov! Closing this PR in favor of #689.

**Pull request closed without merging**
