### PR TITLE
[WIP] identity secrets engine

### PR DESCRIPTION
**Pull request by tiny-dancer**
opening for visibility, still a WIP and verifying.

https://www.vaultproject.io/api/secret/identity/index.html

TODO:
- [X] Entity
- [x] Entity Alias
- [x] Lookup
- [x] documentation
- [x] tests

Out of Scope:
- Group
- Group Alias

### CODE REVIEW

**Comment by jeffwecan** [comment]
I know this is still a work-in-progress, but just wanted to call out that it would be nice to get some usage information for http://hvac.readthedocs.io/ as outlined in https://github.com/hvac/hvac/blob/master/CONTRIBUTING.md#examples whenever you get to that point. 👍

**Comment by jeffwecan** [comment]
Oh and do you think you'll have time to wrap up the changes in this PR over the next week or so? (If so, I'll tag it for the 0.6.5 milestone.)

**Comment by tiny-dancer** [comment]
> over the next week or so

yup that should work!

**Comment by jeffwecan** [comment]
@tiny-dancer: Fair warning, I'm planning on wrapping up the changes you have started here and will push those updates to your branch over the next couple days. 😀

**Comment by tiny-dancer** [comment]
Awesome! Thanks for picking up the slack 🙏

**Pull request merged**
