### PR TITLE
[WIP] [Feature] Implements TOTP API

### PR DESCRIPTION
**Pull request by gabriel-milan**
Implements TOTP API as in https://www.vaultproject.io/api/secret/totp

I've tried my best to match code style.

Still missing:
- Docs
- Tests

Works fine, though

### CODE REVIEW

**Comment by colin-pm** [comment]
@gabriel-milan Thanks for the contribution, the more engines that HVAC supports the better!

If you still plan to add this feature, do you mind pinging me when you have added the docs and tests?

**Comment by xunzhou** [comment]
Didn't noticed this ticket was opened, duplicated some effort.
Mine should include docs and tests, should I open a new PR based on mine?
https://github.com/hvac/hvac/compare/develop...xunzhou:hvac:develop

**Comment by colin-pm** [comment]
@xunzhou That would be great!

**Comment by briantist** [comment]
Hi @gabriel-milan ,

The `hvac` project is simplifying its developer workflow and removing the `develop` branch. Please be aware for future PRs that the project's default branch is now `main`.

Since your PR was opened before this change, I have: 
- updated your PR to merge into the project's `main` branch

Your branch also needs to be rebased against the latest `main` branch (not `develop`), however your branch has conflicts so I did not do that myself.

There is another PR that seems to implement this feature too, but it is also stalled and waiting on the author (#873). 

If you are still interested in pursuing this please rebase and force push. If not that's ok, please let us know (if the other one gets finished up first, it will close this one out), thanks!

**Pull request closed without merging**
