### PR TITLE
feat: add support for `disable_local_ca_jwt` in the Kubernetes auth method

### PR DESCRIPTION
**Pull request by fad3t**
Follow-up of #972 

---

Hi,

First of all thanks for developing this great project :)
I would like to propose my first contribution, about adding the support for the disable_local_ca_jwt in the Kubernetes auth method (cf. https://developer.hashicorp.com/vault/api-docs/auth/kubernetes#disable_local_ca_jwt).

This has been tested and it looks good; please let me know if anything else is needed/missing.

Thanks!
Fred

### CODE REVIEW

**Comment by fad3t** [comment]
@briantist I finally decided to start over this PR, hope that's fine for you :)

**Comment by briantist** [comment]
Hi @fad3t , I'm sorry to report _another_ major branch/workflow update in the `hvac` project, just as you've re-submitted this PR, but I think this will be the last!

The `hvac` project is simplifying its developer workflow and removing the `develop` branch. Please be aware for future PRs that the project's default branch is now `main`.

Since your PR was opened before this change, I have: 
- updated your PR to merge into the project's `main` branch
- rebased your branch against `main` and force-pushed it (**please pull before making any further changes**)

At least this time there's no painful interactive rebasing ;) I believe the changes I made are all that needs to be done.

**Review by briantist — APPROVED** [review]
Thanks very much for submitting this and adding tests!

**Comment by fad3t** [comment]
Thank you @briantist !

**Comment by fad3t** [comment]
@briantist any idea when 1.2.0 will be released?

**Comment by briantist** [comment]
@fad3t it's close, I hope to get back to wrapping up `v1.2.0` soon. I was away for several weeks, so now I have a lot of catching up to do, but it was already close when I left. I am also waiting for reviews from other maintainers on a few things. So I think it will be before the end of this month, but always hard to predict since it is all volunteer time. Thanks for your patience and thanks again for contributing!

**Pull request merged**
